### PR TITLE
Docker doc updates for 6.0

### PR DESCRIPTION
**Pull request by dliappis**
* Clarifications for Openshift and bind-mounts

* Bump docker-compose 2.x format to 2.2

* Combine Docker Toolbox instructions for setting vm.max_map_count for
  both macOS + Windows

* devicemapper is not the default storage driver any more on RHEL

### CODE REVIEW

**Comment by jarpy** [comment]
Thanks. Very helpful stuff. Thanks especially for the Openshift bits, which I didn't grok properly.

This PR contains unrelated patches and merge commits, though.  It's looks you forked from `elastic/master` at a point in the future from `jarpy/master`. I'd like to be able to cleanly squash-merge your edits and mine onto `elastic/master`, so I'm going to try some Git trickery.

**Comment by jarpy** [comment]
OK, [done](https://github.com/jarpy/elasticsearch/commits/master).

For the record:

```
git cherry-pick 3628d4bf8a6a8fc1ef983654f591fd765a1cb745
git rebase elastic/master
git push --force jarpy master
```

**Comment by dliappis** [comment]
Thanks for pasting the commands!

Yes, sorry, I had the latest master here in my PR. I thought since it'd be a squash-merge the commit message would be clean and override the merge commits etc. and when merged with your https://github.com/elastic/elasticsearch/pull/27166, the already present commits in `elastic:master` (e.g. https://github.com/jarpy/elasticsearch/pull/1/commits/8e62314ce4ed062e6476d46b18db41db1d133656)
 won't appear in the PR any more.

**Comment by jarpy** [comment]
You're probably right. My brain just likes to keep the commit graph really clean.

**Pull request merged**
